trigger:
- 'main'

pool:
  vmImage: 'ubuntu-20.04'
  demands:
  - npm

steps:
# Prepare Analysis Configuration task
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'SetUp-SpaceGame'
    scannerMode: 'MSBuild'
    projectKey: 'Space_Game_-_web_Space_Game_-_web_-_Release_AYJ_0WjCnjBiSMiKBr8R'

# Run Code Analysis task
- task: SonarQubeAnalyze@5

# Publish Quality Gate Result task
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
